language: node_js
node_js:
- '4'
addons:
  sauce_connect: true
before_script:
- npm run start &
after_success:
- bash <(curl -s https://codecov.io/bash)
after_script:
- pkill node
before_deploy:
- zip -q -x .git\* node_modules/\* -r collectionsonline *
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIWVLTZ3YIKYYXEYQ
  secret_access_key:
    secure: LlOeI6YZt9ymHViOnVeIchiEoV1xnMr2T27KX4PeOn0IO/M3LnZFtY/OgAZRL7gjZMhDVhyueJ6VfvhGhRRPrb4H5XNg1VL3wEGRtY0E+xOYAgQVaicw01gtQYV9Bd805tV1MC9NkMGGfHouJeODXiQFDYMk02QCu5Jrv/G//e0IL30pqNkJoy6XjGI8kBtlJEhgczHanBbKiFSle4NRboTva7kd3L4t+g/UHF51n3xPuQeWHXv+tzwAgux3go2SdcJBmIt9Q9tHwBlLr/GXL6RZD37pMRrmmG2U8bRDGV7Efeo/Ya99p1LNxY1LG4pLdpOd9J65LZKTn4vduxhuc+gslarXKyf7NQF+wOV4hJn+rRSaPORbJqgoLpsmHOC7Z9QypjZqWa24sZ5ty2uilshsOxZyjFSJM+rssR0o6zxGjkABkXdjYp6Zq/D8YF1mO+xMWvue+ADtdzVp0hhGMt57cDXSgyhRJs7fgkyAkSOclNj8j6y6ZqWH+rIPLzkq2wB1OyTeJzvTti4mKC6mlDWVO0b3N/DdECXokdcdYDEiEGzoT9n28T+s6Le1f1mswk0uWeH7AdGdHxDMg1vK7dQyykHVD1ALtZb6Abhr/hcrD7SFfwpSAqsgvcG/TLqL3BZ4iLdSSqvnBcJtdNlcKifzhtql0tRvNH2zUzJWd+M=
  region: eu-west-1
  app: Collections Online
  env: collectionsonline-staging
  on:
    repo: TheScienceMuseum/collectionsonline
